# model_training/plot_tuning.py
#
# Generates publication-quality figures for hyperparameter tuning results.
# Style: Nature journal aesthetics (minimal, no grid, muted color palette).
#
# Figures always generated (require tuned model pkl files):
#   fig01_roc_curves.pdf              - ROC curves for all 4 tuned models
#   fig02_confusion_matrices.pdf      - Confusion matrices for all 4 tuned models
#   fig03_calibration.pdf             - Calibration curves (reliability diagrams)
#   fig04_feature_importance.pdf      - Feature importance per model
#
# Figures requiring cv_results_<model>.csv (generated by tune.py):
#   fig05_cv_score_distribution.pdf   - CV score distribution: 50 combinations per model
#   fig06_top10_candidates.pdf        - Top 10 hyperparameter combinations per model
#   fig07_hyperparam_rf.pdf           - RF: key hyperparameters vs CV score
#   fig08_hyperparam_gb.pdf           - GB: key hyperparameters vs CV score
#   fig09_hyperparam_svm.pdf          - SVM: key hyperparameters vs CV score
#   fig10_hyperparam_xgb.pdf          - XGB: key hyperparameters vs CV score
#
# Run from the project root:
#   python -m model_training.plot_tuning

import os
import glob
import warnings
import numpy as np
import pandas as pd
import joblib
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.ticker import MaxNLocator
from sklearn.metrics import (
    roc_curve, auc, confusion_matrix, accuracy_score,
    precision_score, recall_score, f1_score, matthews_corrcoef,
    roc_auc_score
)
from sklearn.calibration import calibration_curve
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from amp_identifier.feature_extraction import calculate_physicochemical_features
from amp_identifier.data_io import load_fasta_sequences

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Nature-style rcParams
# ---------------------------------------------------------------------------
mpl.rcParams.update({
    "font.family":        "sans-serif",
    "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
    "font.size":          8,
    "axes.titlesize":     9,
    "axes.labelsize":     8,
    "xtick.labelsize":    7,
    "ytick.labelsize":    7,
    "legend.fontsize":    7,
    "legend.frameon":     False,
    "figure.dpi":         600,
    "savefig.dpi":        600,
    "axes.spines.top":    False,
    "axes.spines.right":  False,
    "axes.grid":          False,
    "xtick.direction":    "out",
    "ytick.direction":    "out",
    "xtick.major.size":   3,
    "ytick.major.size":   3,
    "lines.linewidth":    1.0,
    "patch.linewidth":    0.5,
    "savefig.bbox":       "tight",
    "savefig.pad_inches": 0.05,
})

# Nature column widths: single = 89mm = 3.50in, double = 183mm = 7.20in
COL1 = 3.50
COL2 = 7.20

COLORS = {
    "RF":  "#2166ac",
    "GB":  "#d6604d",
    "SVM": "#4dac26",
    "XGB": "#8856a7",
}
BASELINE_ALPHA = 0.40
TUNED_ALPHA    = 0.88

OUTDIR        = "model_training/tuned_model/figures"
TUNED_DIR     = "model_training/tuned_model"
SAVED_DIR     = "model_training/saved_model"
BASELINE_PATH = os.path.join(SAVED_DIR, "evaluation_report.csv")

DATA_DIR      = "model_training/data"
POSITIVE_FILE = os.path.join(DATA_DIR, "positive_sequences.fasta")
NEGATIVE_FILE = os.path.join(DATA_DIR, "negative_sequences.fasta")
RANDOM_STATE  = 42
TEST_SIZE     = 0.20

FEATURE_NAMES = [
    "Length", "MW", "Charge", "ChargeDensity", "pI",
    "InstabilityInd", "Aromaticity", "AliphaticInd", "BomanInd", "HydrophRatio",
]

MODELS_ORDER = ["RF", "GB", "SVM", "XGB"]


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------
def savefig(fig, name):
    os.makedirs(OUTDIR, exist_ok=True)
    path = os.path.join(OUTDIR, name.replace(".pdf", ".png"))
    fig.savefig(path, dpi=600)
    print(f"  Saved -> {path}")
    plt.close(fig)


def load_test_data():
    """Reproduce the same test split as tune.py (identical random_state)."""
    print("  Loading and splitting data...")
    pos_seqs, pos_ids = load_fasta_sequences(POSITIVE_FILE)
    neg_seqs, neg_ids = load_fasta_sequences(NEGATIVE_FILE)
    sequences = pos_seqs + neg_seqs
    ids       = pos_ids + neg_ids
    labels    = [1] * len(pos_seqs) + [0] * len(neg_seqs)

    features_df = calculate_physicochemical_features(sequences, ids)
    features_df["label"] = labels
    X = features_df.drop(columns=["ID", "sequence", "label"]).fillna(0)
    y = features_df["label"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_test_sc = pd.DataFrame(
        scaler.transform(X_test), columns=X_test.columns, index=X_test.index
    )
    X_train_sc = pd.DataFrame(
        scaler.transform(X_train), columns=X_train.columns, index=X_train.index
    )
    return X_train_sc, X_test_sc, y_train, y_test


def load_tuned_models():
    models = {}
    for name in MODELS_ORDER:
        path = os.path.join(TUNED_DIR, f"amp_model_{name.lower()}_tuned.pkl")
        if os.path.exists(path):
            models[name] = joblib.load(path)
        else:
            print(f"  Warning: {path} not found, skipping {name}.")
    return models


def load_baseline_models():
    models = {}
    for name in MODELS_ORDER:
        path = os.path.join(SAVED_DIR, f"amp_model_{name.lower()}.pkl")
        if os.path.exists(path):
            models[name] = joblib.load(path)
    return models


def load_all_results():
    result_files = glob.glob(os.path.join(TUNED_DIR, "result_*.csv"))
    if not result_files:
        return None, None
    tuned = pd.concat([pd.read_csv(f) for f in result_files], ignore_index=True)
    if not os.path.exists(BASELINE_PATH):
        return tuned, None
    baseline = pd.read_csv(BASELINE_PATH)
    baseline = baseline.rename(columns={"f1_score": "f1"})
    return tuned, baseline


def load_cv_results(model_name):
    path = os.path.join(TUNED_DIR, f"cv_results_{model_name.lower()}.csv")
    if not os.path.exists(path):
        return None
    return pd.read_csv(path)


# ---------------------------------------------------------------------------
# Fig 01 - Performance comparison: baseline vs tuned
# ---------------------------------------------------------------------------
def fig01_performance_comparison(tuned, baseline):
    metrics = ["auc_roc", "mcc", "f1"]
    labels  = ["AUC-ROC", "MCC", "F1-score"]

    fig, axes = plt.subplots(1, 3, figsize=(COL2, 2.4))

    for ax, metric, label in zip(axes, metrics, labels):
        x     = np.arange(len(MODELS_ORDER))
        width = 0.35

        for i, model in enumerate(MODELS_ORDER):
            color = COLORS[model]
            if baseline is not None:
                brow = baseline[baseline["model"].str.upper() == model]
                if not brow.empty and metric in brow.columns:
                    ax.bar(x[i] - width / 2, float(brow[metric].values[0]),
                           width, color=color, alpha=BASELINE_ALPHA, linewidth=0)
            trow = tuned[tuned["model"].str.upper() == model]
            if not trow.empty and metric in trow.columns:
                ax.bar(x[i] + width / 2, float(trow[metric].values[0]),
                       width, color=color, alpha=TUNED_ALPHA, linewidth=0)

        ax.set_xticks(x)
        ax.set_xticklabels(MODELS_ORDER)
        ax.set_ylabel(label)
        ax.yaxis.set_major_locator(MaxNLocator(5, prune="lower"))

        all_vals = []
        for model in MODELS_ORDER:
            for df in [baseline, tuned]:
                if df is not None:
                    row = df[df["model"].str.upper() == model]
                    if not row.empty and metric in row.columns:
                        all_vals.append(float(row[metric].values[0]))
        if all_vals:
            ax.set_ylim(max(0, min(all_vals) - 0.03), min(1.0, max(all_vals) + 0.03))

    patch_base  = mpatches.Patch(color="gray", alpha=BASELINE_ALPHA, label="Baseline")
    patch_tuned = mpatches.Patch(color="gray", alpha=TUNED_ALPHA, label="Tuned")
    model_patches = [mpatches.Patch(color=COLORS[m], label=m) for m in MODELS_ORDER]
    axes[1].legend(handles=[patch_base, patch_tuned] + model_patches,
                   loc="lower center", bbox_to_anchor=(0.5, -0.34),
                   ncol=5, handlelength=1.2, handletextpad=0.5, columnspacing=0.8)

    fig.suptitle("Baseline vs. optimized hyperparameters", fontsize=9, y=1.02)
    savefig(fig, "fig01_performance_comparison.pdf")


# ---------------------------------------------------------------------------
# Fig 02 - ROC curves
# ---------------------------------------------------------------------------
def fig02_roc_curves(models, X_test, y_test):
    fig, ax = plt.subplots(figsize=(COL1, COL1))

    for name, model in models.items():
        y_proba = model.predict_proba(X_test)[:, 1]
        fpr, tpr, _ = roc_curve(y_test, y_proba)
        roc_auc = auc(fpr, tpr)
        ax.plot(fpr, tpr, color=COLORS[name], linewidth=1.2,
                label=f"{name} (AUC = {roc_auc:.3f})")

    ax.plot([0, 1], [0, 1], color="#aaaaaa", linewidth=0.8, linestyle="--")
    ax.set_xlim([-0.02, 1.02])
    ax.set_ylim([-0.02, 1.02])
    ax.set_xlabel("False positive rate")
    ax.set_ylabel("True positive rate")
    ax.set_title("Receiver operating characteristic (ROC) curves", fontsize=9)
    ax.legend(loc="lower right")

    savefig(fig, "fig01_roc_curves.pdf")


# ---------------------------------------------------------------------------
# Fig 03 - Confusion matrices
# ---------------------------------------------------------------------------
def fig03_confusion_matrices(models, X_test, y_test):
    n = len(models)
    fig, axes = plt.subplots(1, n, figsize=(2.6 * n, 2.6))
    if n == 1:
        axes = [axes]

    for idx, (ax, (name, model)) in enumerate(zip(axes, models.items())):
        y_pred = model.predict(X_test)
        cm = confusion_matrix(y_test, y_pred)
        tn, fp, fn, tp = cm.ravel()
        mat = np.array([[tn, fp], [fn, tp]])

        color = COLORS[name]
        cmap  = mpl.colors.LinearSegmentedColormap.from_list(
            "custom", ["#ffffff", color], N=256
        )
        ax.imshow(mat, cmap=cmap, vmin=0, aspect="auto")

        cell_labels = [["TN", "FP"], ["FN", "TP"]]
        for i in range(2):
            for j in range(2):
                val = mat[i, j]
                text_color = "white" if val > mat.max() * 0.6 else "#333333"
                ax.text(j, i, f"{cell_labels[i][j]}\n{val}",
                        ha="center", va="center", fontsize=8,
                        color=text_color, fontweight="bold")

        ax.set_xticks([0, 1])
        ax.set_yticks([0, 1])
        ax.set_xticklabels(["Neg.", "Pos."], fontsize=7)
        if idx == 0:
            ax.set_yticklabels(["Neg.", "Pos."], fontsize=7)
        else:
            ax.set_yticklabels(["", ""])

        mcc  = matthews_corrcoef(y_test, y_pred)
        acc  = accuracy_score(y_test, y_pred)
        ax.set_title(f"{name}\nAcc={acc:.3f}  MCC={mcc:.3f}", fontsize=8)

    fig.suptitle("Confusion matrices on held-out test set", fontsize=9)
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    savefig(fig, "fig02_confusion_matrices.pdf")


# ---------------------------------------------------------------------------
# Fig 04 - Calibration curves
# ---------------------------------------------------------------------------
def fig04_calibration(models, X_test, y_test):
    fig, ax = plt.subplots(figsize=(COL1, COL1))

    for name, model in models.items():
        y_proba = model.predict_proba(X_test)[:, 1]
        frac_pos, mean_pred = calibration_curve(y_test, y_proba, n_bins=10)
        ax.plot(mean_pred, frac_pos, color=COLORS[name],
                linewidth=1.2, marker="o", markersize=3, label=name)

    ax.plot([0, 1], [0, 1], color="#aaaaaa", linewidth=0.8,
            linestyle="--", label="Perfect calibration")
    ax.set_xlim([-0.02, 1.02])
    ax.set_ylim([-0.02, 1.02])
    ax.set_xlabel("Mean predicted probability")
    ax.set_ylabel("Fraction of positives")
    ax.set_title("Probability calibration (reliability diagram)", fontsize=9)
    ax.legend(loc="upper left")

    savefig(fig, "fig03_calibration.pdf")


# ---------------------------------------------------------------------------
# Fig 05 - Feature importance
# ---------------------------------------------------------------------------
def fig05_feature_importance(models, X_train, y_train, X_test, y_test):
    n = len(models)
    ncols = 2
    nrows = (n + 1) // 2
    fig, axes = plt.subplots(nrows, ncols, figsize=(COL2, nrows * 3.2))
    axes = np.array(axes).flatten()

    for idx, (name, model) in enumerate(models.items()):
        ax = axes[idx]
        color = COLORS[name]

        if hasattr(model, "feature_importances_"):
            importances = model.feature_importances_
            stds = np.zeros_like(importances)
        else:
            # Permutation importance for SVM
            print(f"  Computing permutation importance for {name} (may take ~1 min)...")
            result = permutation_importance(
                model, X_test, y_test,
                n_repeats=10, random_state=RANDOM_STATE, n_jobs=-1,
                scoring="roc_auc"
            )
            importances = result.importances_mean
            stds = result.importances_std

        order = np.argsort(importances)
        names_sorted = [FEATURE_NAMES[i] for i in order]
        imp_sorted   = importances[order]
        std_sorted   = stds[order]

        y_pos = np.arange(len(names_sorted))
        ax.barh(y_pos, imp_sorted, xerr=std_sorted if stds.any() else None,
                color=color, alpha=TUNED_ALPHA, linewidth=0,
                error_kw={"elinewidth": 0.7, "capsize": 2, "ecolor": "#555555"})
        ax.set_yticks(y_pos)
        ax.set_yticklabels(names_sorted, fontsize=6)
        ax.set_xlabel("Importance" if hasattr(model, "feature_importances_")
                      else "Permutation importance (AUC-ROC)", fontsize=7)
        ax.set_title(name, fontsize=9)
        ax.spines["left"].set_visible(False)
        ax.tick_params(left=False)

    # Hide unused axes if n is odd
    for idx in range(n, len(axes)):
        axes[idx].set_visible(False)

    fig.suptitle("Physicochemical feature importance per classifier", fontsize=9)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    savefig(fig, "fig04_feature_importance.pdf")


# ---------------------------------------------------------------------------
# Fig 06 - CV score distribution across 50 candidates
# ---------------------------------------------------------------------------
def fig06_cv_score_distribution():
    data = {}
    for m in ["rf", "gb", "svm", "xgb"]:
        cv = load_cv_results(m)
        if cv is not None and "mean_test_score" in cv.columns:
            data[m.upper()] = cv[["mean_test_score", "std_test_score"]]

    if not data:
        print("  Skipping fig05: cv_results CSVs not found. Re-run tune.py first.")
        return

    fig, ax = plt.subplots(figsize=(COL1, 2.8))
    positions = np.arange(len(data))

    for pos, (model, df) in zip(positions, data.items()):
        color  = COLORS[model]
        scores = df["mean_test_score"].values
        stds   = df["std_test_score"].values

        # Individual points with jitter
        rng    = np.random.default_rng(42)
        jitter = rng.uniform(-0.13, 0.13, size=len(scores))
        ax.errorbar(np.full_like(scores, pos) + jitter, scores,
                    yerr=stds, fmt="none", ecolor=color, alpha=0.25,
                    elinewidth=0.5, capsize=0)
        ax.scatter(np.full_like(scores, pos) + jitter, scores,
                   color=color, alpha=0.55, s=8, linewidths=0, zorder=3)

        # Median line
        med = np.median(scores)
        ax.hlines(med, pos - 0.28, pos + 0.28,
                  color=color, linewidth=1.8, zorder=4)

        # Best candidate marker
        best_idx = np.argmax(scores)
        ax.scatter([pos + jitter[best_idx]], [scores[best_idx]],
                   color=color, s=30, marker="*", zorder=5, linewidths=0)

    ax.set_xticks(positions)
    ax.set_xticklabels(list(data.keys()))
    ax.set_ylabel("CV AUC-ROC (mean ± SD across 5 folds)")
    ax.set_title("CV AUC-ROC distribution across 50 hyperparameter candidates\n"
                 "(line = median, star = best)", fontsize=8)

    savefig(fig, "fig05_cv_score_distribution.pdf")


# ---------------------------------------------------------------------------
# Fig 07 - Top 10 candidates per model
# ---------------------------------------------------------------------------
def fig07_top10_candidates():
    available = {}
    for m in ["rf", "gb", "svm", "xgb"]:
        cv = load_cv_results(m)
        if cv is not None and "mean_test_score" in cv.columns:
            available[m.upper()] = cv

    if not available:
        print("  Skipping fig07: cv_results CSVs not found. Re-run tune.py first.")
        return

    n = len(available)
    ncols = 2
    nrows = (n + 1) // 2
    fig, axes = plt.subplots(nrows, ncols, figsize=(COL2, nrows * 3.0))
    axes = np.array(axes).flatten()

    for idx, (model, cv) in enumerate(available.items()):
        ax = axes[idx]
        color = COLORS[model]
        top10 = cv.nlargest(10, "mean_test_score").reset_index(drop=True)
        y_pos = np.arange(len(top10))

        ax.barh(y_pos, top10["mean_test_score"],
                xerr=top10["std_test_score"],
                color=color, alpha=TUNED_ALPHA, linewidth=0,
                error_kw={"elinewidth": 0.7, "capsize": 2, "ecolor": "#555555"})

        ax.set_yticks(y_pos)
        ax.set_yticklabels([f"#{i+1}" for i in range(len(top10))], fontsize=6.5)
        ax.set_xlabel("CV AUC-ROC", fontsize=7)
        ax.set_title(f"{model}: top 10 hyperparameter candidates", fontsize=9)
        ax.invert_yaxis()

        # Mark the best
        ax.barh([0], [top10.loc[0, "mean_test_score"]], color=color,
                alpha=1.0, linewidth=0)

        ax.spines["left"].set_visible(False)
        ax.tick_params(left=False)

        # Tight x range around top10 scores
        all_vals = top10["mean_test_score"].values
        lo = max(0, all_vals.min() - 0.01)
        hi = min(1.0, all_vals.max() + 0.015)
        ax.set_xlim(lo, hi)

    for idx in range(n, len(axes)):
        axes[idx].set_visible(False)

    fig.suptitle("Top 10 hyperparameter combinations by CV AUC-ROC", fontsize=9)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    savefig(fig, "fig06_top10_candidates.pdf")


# ---------------------------------------------------------------------------
# Fig 08-10 - Hyperparameter exploration scatter plots
# ---------------------------------------------------------------------------
def fig_hyperparam(model_name, param_cols, log_params, fig_num):
    cv = load_cv_results(model_name)
    if cv is None:
        print(f"  Skipping fig{fig_num:02d}: cv_results_{model_name}.csv not found.")
        return

    color     = COLORS[model_name.upper()]
    score_col = "mean_test_score"
    std_col   = "std_test_score"
    best_idx  = cv[score_col].idxmax()

    # Filter to numeric params only for scatter
    numeric_params = []
    for p in param_cols:
        col = f"param_{p}"
        if col in cv.columns:
            vals = pd.to_numeric(cv[col], errors="coerce")
            if vals.notna().sum() >= 5:
                numeric_params.append(p)

    if not numeric_params:
        print(f"  Skipping fig{fig_num:02d}: no numeric params found.")
        return

    n = len(numeric_params)
    fig, axes = plt.subplots(1, n, figsize=(COL1 * n, 2.6))
    if n == 1:
        axes = [axes]

    for ax, param in zip(axes, numeric_params):
        col  = f"param_{param}"
        vals = pd.to_numeric(cv[col], errors="coerce")
        mask = vals.notna()
        x    = vals[mask].values
        y    = cv.loc[mask, score_col].values
        yerr = cv.loc[mask, std_col].values

        ax.errorbar(x, y, yerr=yerr, fmt="o", color=color,
                    alpha=0.50, markersize=4, linewidth=0,
                    capsize=1.5, elinewidth=0.6, ecolor=color)

        # Highlight best candidate if it has a numeric value for this param
        if mask[best_idx]:
            ax.scatter([vals[best_idx]], [cv.loc[best_idx, score_col]],
                       color=color, s=45, zorder=5, linewidths=0, marker="*")

        if param in log_params:
            ax.set_xscale("log")

        ax.set_xlabel(param.replace("_", " "))
        ax.set_ylabel("CV AUC-ROC")
        ax.set_title(f"{model_name.upper()}: {param.replace('_', ' ')} vs. CV AUC-ROC",
                     fontsize=9)

    fig.suptitle(f"{model_name.upper()} — hyperparameter search space (star = selected optimum)",
                 fontsize=9, y=1.04)
    savefig(fig, f"fig{fig_num:02d}_hyperparam_{model_name.lower()}.pdf")


# ---------------------------------------------------------------------------
# Fig 11 - Metrics comparison: all models + ensemble
# ---------------------------------------------------------------------------
def fig11_metrics_comparison(models, X_test, y_test):
    from scipy.stats import mode as scipy_mode

    metrics_def = [
        ("accuracy",    "Accuracy"),
        ("precision",   "Precision"),
        ("recall",      "Sensitivity"),
        ("specificity", "Specificity"),
        ("f1",          "F1-score"),
        ("mcc",         "MCC"),
        ("auc_roc",     "AUC-ROC"),
    ]

    def compute_metrics(y_true, y_pred, y_proba):
        tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
        return {
            "accuracy":    accuracy_score(y_true, y_pred),
            "precision":   precision_score(y_true, y_pred, zero_division=0),
            "recall":      recall_score(y_true, y_pred, zero_division=0),
            "specificity": tn / (tn + fp) if (tn + fp) > 0 else 0.0,
            "f1":          f1_score(y_true, y_pred, zero_division=0),
            "mcc":         matthews_corrcoef(y_true, y_pred),
            "auc_roc":     roc_auc_score(y_true, y_proba),
        }

    all_preds  = {}
    all_probas = {}
    results    = {}

    for name, model in models.items():
        y_pred  = model.predict(X_test)
        y_proba = model.predict_proba(X_test)[:, 1]
        all_preds[name]  = y_pred
        all_probas[name] = y_proba
        results[name]    = compute_metrics(y_test, y_pred, y_proba)

    # Ensemble: majority vote; mean proba for AUC-ROC
    if len(models) > 1:
        preds_matrix = np.column_stack(list(all_preds.values()))
        ensemble_pred, _ = scipy_mode(preds_matrix, axis=1, keepdims=True)
        ensemble_pred    = ensemble_pred.ravel().astype(int)
        ensemble_proba   = np.mean(list(all_probas.values()), axis=0)
        results["Ensemble"] = compute_metrics(y_test, ensemble_pred, ensemble_proba)

    model_names = list(results.keys())
    ensemble_color = "#555555"
    colors = [COLORS.get(m, ensemble_color) for m in model_names]

    n_metrics = len(metrics_def)
    n_models  = len(model_names)
    x         = np.arange(n_metrics)
    total_width = 0.75
    bar_width   = total_width / n_models

    fig, ax = plt.subplots(figsize=(COL2, 3.0))

    for i, (name, color) in enumerate(zip(model_names, colors)):
        vals = [results[name][key] for key, _ in metrics_def]
        offset = (i - (n_models - 1) / 2) * bar_width
        alpha  = 1.0 if name == "Ensemble" else TUNED_ALPHA
        ax.bar(x + offset, vals, bar_width,
               color=color, alpha=alpha, linewidth=0, label=name)

    ax.set_xticks(x)
    ax.set_xticklabels([lbl for _, lbl in metrics_def], fontsize=7)
    ax.set_ylabel("Score")
    ax.set_ylim(0, 1.08)
    ax.yaxis.set_major_locator(MaxNLocator(6, prune="upper"))

    # Reference threshold line at 90%
    ax.axhline(0.90, color="#b22222", linewidth=0.9, linestyle="--", zorder=0)
    ax.text(-0.55, 0.90 + 0.008, "90%",
            color="#b22222", fontsize=6.5, va="bottom", ha="left")

    legend_patches = [
        mpatches.Patch(color=COLORS.get(m, ensemble_color),
                       alpha=1.0 if m == "Ensemble" else TUNED_ALPHA, label=m)
        for m in model_names
    ]
    ax.legend(handles=legend_patches,
              loc="upper center", bbox_to_anchor=(0.5, -0.13),
              ncol=n_models, handlelength=1.0,
              handletextpad=0.4, columnspacing=0.7)

    ax.set_title("Classification performance across tuned models and ensemble vote",
                 fontsize=9)
    fig.tight_layout(rect=[0, 0.08, 1, 1])
    savefig(fig, "fig11_metrics_comparison.pdf")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    os.makedirs(OUTDIR, exist_ok=True)

    print("Loading test data (reproducible split)...")
    X_train, X_test, y_train, y_test = load_test_data()

    print("Loading tuned models...")
    tuned_models = load_tuned_models()
    if not tuned_models:
        print("No tuned models found. Run tune.py first.")
        return

    # ---- Figures that always run ----
    print("\nFig 01: ROC curves...")
    fig02_roc_curves(tuned_models, X_test, y_test)

    print("\nFig 02: Confusion matrices...")
    fig03_confusion_matrices(tuned_models, X_test, y_test)

    print("\nFig 03: Calibration curves...")
    fig04_calibration(tuned_models, X_test, y_test)

    print("\nFig 04: Feature importance...")
    fig05_feature_importance(tuned_models, X_train, y_train, X_test, y_test)

    # ---- Figures that require cv_results_ ----
    print("\nFig 05: CV score distribution...")
    fig06_cv_score_distribution()

    print("\nFig 06: Top 10 candidates...")
    fig07_top10_candidates()

    print("\nFig 07: RF hyperparameter exploration...")
    fig_hyperparam("rf",
                   param_cols=["n_estimators", "max_depth", "min_samples_split", "max_features"],
                   log_params=[],
                   fig_num=7)

    print("\nFig 08: GB hyperparameter exploration...")
    fig_hyperparam("gb",
                   param_cols=["n_estimators", "learning_rate", "max_depth", "subsample"],
                   log_params=["learning_rate"],
                   fig_num=8)

    print("\nFig 09: SVM hyperparameter exploration...")
    fig_hyperparam("svm",
                   param_cols=["C", "gamma"],
                   log_params=["C", "gamma"],
                   fig_num=9)

    print("\nFig 10: XGBoost hyperparameter exploration...")
    fig_hyperparam("xgb",
                   param_cols=["n_estimators", "learning_rate", "max_depth",
                               "reg_alpha", "reg_lambda"],
                   log_params=["learning_rate", "reg_alpha", "reg_lambda"],
                   fig_num=10)

    print("\nFig 11: Model metrics comparison (all models + ensemble)...")
    fig11_metrics_comparison(tuned_models, X_test, y_test)

    print(f"\nAll figures saved to: {OUTDIR}")


if __name__ == "__main__":
    main()
